compiler=g++
flags=
all: sam.o sock.o util.o
	ar rcs libSimplySAM.a *.o
sam.o: sam.cpp
	$(compiler) $(flags) sam.cpp -c
sock.o: sock.cpp
	$(compiler) $(flags) sock.cpp -c
util.o: util.cpp
	$(compiler) $(flags) util.cpp -c
