compiler=g++
flags=
all: main.o sam.o sock.o util.o
	ar rcs libSimplySAM.a *.o
main.o: main.cpp
	$(compiler) $(flags) main.cpp -c
sam.o: sam.cpp
	$(compiler) $(flags) sam.cpp -c
sock.o: sock.cpp
	$(compiler) $(flags) sock.cpp -c
util.o: util.cpp
	$(compiler) $(flags) util.cpp -c
